### ISSUE TITLE
Request - Add support for Fidelix FM25Q04A

### ISSUE THREAD

**Issue by tantoinet** [Blinkinlabs/BlinkinlabsAltiumLibrary#1]
Hello,

Can you please add support for FIDELIX FM25Q04A?
I've dumped the FM25Q04A using the FM25Q08A profile and a CH341A programmer with a SOIC8 clip. I'm not sure if I've dumped all its content correctly though

Thanks

**Comment by cibomahto** [comment]
I think you have the wrong repository, this is a schematic and footprint collection for Altium

**Comment by tantoinet** [comment]
true, sorry, I thought I was still on https://github.com/nofeletru/UsbAsp-flash/releases
